controllers/DemoController.php
<?php


namespace app\controllers;


use yii\web\Controller;

class DemoController extends Controller
{
    public function actionRedirect(){

        return $this->render('redirect');
    }

    public function actionIndex(){
        return $this->render('index');
    }
}

controllers/DrawController.php
<?php


namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\services\DrawService;
use yii\helpers\Json;
class DrawController extends Controller
{
    private $drawService;
    public function __construct($id, $module, $config = [],DrawService $drawService)
    {
        parent::__construct($id, $module, $config);
        $this->drawService = $drawService;
    }

    public function actionIndex(){
      //  Yii::info('Using index page');
        return $this->render('index');

    }

    public function actionData(){
        if(Yii::$app->request->isAjax) {
            $shapes = $this->drawService->getShapeData();
//            var_dump($shapes);
        //    Yii::info('Get data from database');
            return Json::encode($shapes);
        }
    }

    //get max id in table
    public function actionId(){
        if(Yii::$app->request->isAjax){
            $data = $this->drawService->getMaxShapeId(); // Object {"id":24,"shape_name":"shape0","points":"259,208,190,293,351,367,383,302"}
            return Json::encode($data['id']);
        }

    }

    


}

controllers/PointController.php
<?php


namespace app\controllers;

use yii;
use app\models\Point;
use yii\web\Controller;
use app\services\PointService;

class PointController extends Controller
{
    private $pointService;
    public function __construct($id, $module, $config = [],PointService $pointService)
    {
        parent::__construct($id, $module, $config);
        $this->pointService=$pointService;
    }

    public function actionCreate(){
        if(Yii::$app->request->isAjax){
            $data = Yii::$app->request->post();
            $shape = $this->pointService->getShapeById(intval($data['shape_id']));
            $point = new Point();
            $point->x=$data['x'];
            $point->y=$data['y'];
            $point->link('shape', $shape);
            $point->save();

        }
    }
}

controllers/ShapeController.php
<?php


namespace app\controllers;

use app\services\ShapeService;
use Yii;
use app\models\Shape;
use yii\web\Controller;
use yii\helpers\Json;
use yii\web\Response;

class ShapeController extends Controller
{
    private $shapeService;
    public function __construct($id, $module, $config = [],ShapeService $shapeService)
    {
        parent::__construct($id, $module, $config);
        $this->shapeService=$shapeService;
    }

    //insert constructionId,orderNumber and isUser
    public function actionCreate(){
       if (Yii::$app->request->isAjax) {
           $data = Yii::$app->request->post();
           $model = new Shape();
           $values = [
                'shape_name' => $data['shape_name'],
                'points' => $data['points']
           ];
           $model->attributes = $values;
           $model->save();
         //  var_dump($result);
//            return Json::encode($data)
       }
   }

   public function actionUpdate(){
       if(Yii::$app->request->isAjax){
           $request = Yii::$app->request->post();
           $data = $this->shapeService->formatRequestAjax($request);
           $shape = Shape::findOne($data['id']);
           $pointString = $this->shapeService->handleUpdatePoints($shape,$data);
           $affectedRow = $shape->updateAttributes(['points' => $pointString]);
           if($affectedRow > 0)
               $response = ['result' => 1];
           else
               $response = ['result' => 0];

           return Json::encode($response);
       }
   }

   public function actionDelete(){
        if(Yii::$app->request->isAjax){
            $request = Yii::$app->request->post();
            $affectedRow = Shape::findOne($request['id'])->delete();
            if($affectedRow > 0)
                $result = 1 ;

            else
                $result = 0 ;
            return Json::encode($result);
        }
   }




}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;

use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrapper">
    <div class="container-fluid">
        <?= $content ?>
    </div>
</div>



<?php $this->endBody() ?>
<script>
    var urlCreateShape = "<?php echo Yii::$app->request->baseUrl. '/shape/create' ?>";
    var urlCreatePoint = "<?php echo Yii::$app->request->baseUrl. '/point/create' ?>";
    var urlData = "<?php echo Yii::$app->request->baseUrl. '/draw/data' ?>";
    var urlGetMaxId = "<?php echo Yii::$app->request->baseUrl. '/draw/id' ?>";
    var urlUpdateShape = "<?php echo Yii::$app->request->baseUrl. '/shape/update' ?>";
    var urlDeleteShape = "<?php echo Yii::$app->request->baseUrl. '/shape/delete' ?>";
    var csrf = "<?=Yii::$app->request->getCsrfToken()?>";
    var urlIndex = "<?php echo Yii::$app->request->baseUrl. '/demo/index' ?>";
</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main1.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>

    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">

    <div class="container">

        <?= $content ?>
    </div>
</div>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>